
// This file has been generated by the GUI designer. Do not modify.
namespace AnanseGtk
{
	public partial class Presenter
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView keyTree;
		private global::Gtk.Label GtkLabel;
		private global::Crawler.Crawler crawler1;
		private global::Gtk.VPaned vpaned3;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView stackTree;
		private global::Gtk.Label GtkLabel1;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView pathTree;
		private global::Gtk.Label GtkLabel2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AnanseGtk.Presenter
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "AnanseGtk.Presenter";
			// Container child AnanseGtk.Presenter.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 621;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 294;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 203;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.keyTree = new global::Gtk.TreeView ();
			this.keyTree.CanFocus = true;
			this.keyTree.Name = "keyTree";
			this.GtkScrolledWindow.Add (this.keyTree);
			this.GtkAlignment2.Add (this.GtkScrolledWindow);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Keys</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel;
			this.vpaned1.Add (this.frame3);
			global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.frame3]));
			w6.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.crawler1 = new global::Crawler.Crawler ();
			this.crawler1.Events = ((global::Gdk.EventMask)(256));
			this.crawler1.Name = "crawler1";
			this.crawler1.RulesHint = false;
			this.crawler1.Editable = false;
			this.crawler1.ZoomIn = false;
			this.vpaned1.Add (this.crawler1);
			this.hpaned2.Add (this.vpaned1);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.vpaned1]));
			w8.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vpaned3 = new global::Gtk.VPaned ();
			this.vpaned3.CanFocus = true;
			this.vpaned3.Name = "vpaned3";
			this.vpaned3.Position = 208;
			// Container child vpaned3.Gtk.Paned+PanedChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.stackTree = new global::Gtk.TreeView ();
			this.stackTree.CanFocus = true;
			this.stackTree.Name = "stackTree";
			this.GtkScrolledWindow1.Add (this.stackTree);
			this.GtkAlignment.Add (this.GtkScrolledWindow1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Stack</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.vpaned3.Add (this.frame1);
			global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.vpaned3 [this.frame1]));
			w12.Resize = false;
			// Container child vpaned3.Gtk.Paned+PanedChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.pathTree = new global::Gtk.TreeView ();
			this.pathTree.CanFocus = true;
			this.pathTree.Name = "pathTree";
			this.GtkScrolledWindow2.Add (this.pathTree);
			this.GtkAlignment1.Add (this.GtkScrolledWindow2);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Path</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.vpaned3.Add (this.frame2);
			this.hpaned2.Add (this.vpaned3);
			this.hpaned1.Add (this.hpaned2);
			global::Gtk.Paned.PanedChild w18 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.hpaned2]));
			w18.Resize = false;
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w19.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
